### ISSUE TITLE
Don't download twice codecov in coverage_build.yml

### ISSUE THREAD

**Issue by vvaltchev** [vvaltchev/tilck#119]
Currently, https://uploader.codecov.io/latest/linux/codecov is downloaded twice: once by the command `./build/scripts/generate_kernel_coverage_report --codecov` and once explicitly. It would be better to skip the 2nd download and just re-run the coverage tool from `./build/tmp/covecov`.

@michelececcacci I guess this is for you to fix ;-)

**Comment by michelececcacci** [comment]
I can take it, no problem!

**Comment by vvaltchev** [comment]
Thanks @michelececcacci !! :-)

**Comment by vvaltchev** [comment]
Thanks!!
