### ISSUE TITLE
Move other/musl-gcc and other/musl-g++ to scripts/templates

### ISSUE THREAD

**Issue by vvaltchev** [vvaltchev/tilck#135]
The `other/musl-gcc` and `other/musl-g++` template scripts are currently in the wrong place. The fix requires simply moving those two files to `scripts/templates` and replacing their paths in the `other/cmake/gen_config_pre.cmake` file:

Code snippet:

```cmake
smart_config_file(
   ${CMAKE_SOURCE_DIR}/other/musl-gcc
   ${MUSL_GCC}
)

smart_config_file(
   ${CMAKE_SOURCE_DIR}/other/musl-g++
   ${MUSL_GXX}
)
```

**Comment by francescoparra** [comment]
Hello, may I take this issue?

**Comment by vvaltchev** [comment]
Hello @francescoparra. Sure, absolutely :-)

**Comment by vvaltchev** [comment]
Closing this issue, as it has been fixed by commit https://github.com/vvaltchev/tilck/commit/32b571d5625c04eefb9bf7a3ba732dc6c1e2cf53
