### ISSUE TITLE
Add unit tests for functions in string_util.c

### ISSUE THREAD

**Issue by vvaltchev** [vvaltchev/tilck#145]
As it can be seen here: https://app.codecov.io/gh/vvaltchev/tilck/blob/master/common/string_util.c, those functions do not have full coverage, while it will good to have that.

One of the technical problems here is that those functions have the same name as the standard libc functions (e.g. strcpy(), strcat() etc.). Therefore, they cannot be exported to unit tests directly. The solution to this problem is simple:
 - add a `tilck_` prefix to those functions
 - under `#if !defined(TESTING) && !defined(USERMODE_APP)`, create alias symbols using the GCC alias attribute.

Example:
```C
int tilck_add(int a, int b)
{
	return a+b;
}

#if !defined(TESTING) && !defined(USERMODE_APP)
int add(int a, int b) __attribute__((alias("tilck_add"))); 
#endif
```

This way, it will be trivial to test those functions from C++, using they full name (tilck_strcmp, tilck_strcat, etc.). The goal is having 100% line coverage.

**Comment by michelececcacci** [comment]
This should be closed as completed

**Comment by vvaltchev** [comment]
Sure.
