### ISSUE TITLE
Add tests for save_param_buffer() and dump_param_buffer()

### ISSUE THREAD

**Issue by vvaltchev** [vvaltchev/tilck#147]
As it can be seen here: https://app.codecov.io/gh/vvaltchev/tilck/blob/master/modules/tracing/ptype_buffer.c, both the functions don't have enough coverage. 

It will be great to write unit tests for both the functions. Hints:
1.  Both the functions are `static` and need to be made `STATIC` in order to be used from unit tests
2.  Testing `save_param_buffer()` requires mocking `copy_str_from_user()` and `copy_from_user()`, in order to make them fail.
3. As an example of a similar issue, see: https://github.com/vvaltchev/tilck/issues/120

**Comment by michelececcacci** [comment]
I'm taking this

**Comment by rviu** [comment]
Hi, I would like to take this up

**Comment by vvaltchev** [comment]
Hello @rviu, you're welcome to take this issue.
